version: '3.1'

networks:
  mysql_networks:
    external: true

services:
  web:
    #zhuchunshu/sforum:v2 or ghcr.io/zhuchunshu/sforum:v2
    build: .
    ports:
      - "9501:9501"
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
      - DB_DATABASE=sforum
      - DB_USERNAME=sforum
      - DB_PASSWORD=123456

    networks:
      - mysql_networks
    volumes:
      - ./:/data/www