version: '3.8'

services:
  db:
    image: mysql
    restart: always
    privileged: true
    volumes:
      - /Users/inkedus/Desktop/App/Docker/Forum:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'forum2'   
      MYSQL_USER: 'forum2'
      MYSQL_PASSWORD: 'forum2'      
      MYSQL_ROOT_PASSWORD: 'forum2'
    command: [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_general_ci',
        '--max_connections=3000'
    ]
    networks:
      - default

  redis:
    image: "redis:alpine"
    volumes:
       - db_data:/var/lib/redis
    networks:
      - default
       
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - default

  web:
    build: .
    ports:
      - "9501:9501"
      - "9502:9502"
      - "9503:9503"
    environment:
      APP_ENV: dev
      SCAN_CACHEABLE: (false)
      DB_DATABASE: forum2
      DB_USERNAME: forum2
      DB_PASSWORD: forum2
      REDIS_HOST: redis
    depends_on:
      - db
      - redis
    networks:
      - default
    links:
      - db

volumes:
  db_data:
  web_data:

networks:
  default: