name: 自动发布Release

on:
  push:
    tags:
    - 'v*'
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Get version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      
    - name: Checkout source
      uses: actions/checkout@v3
      
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1 
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      with:
        tag_name: ${{ steps.get_version.outputs.VERSION }}
        name: ${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
        
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        platforms: linux/arm,linux/arm64,linux/amd64,darwin,windows/amd64
        push: true
        tags: |
          zhuchunshu/sforum:${{ github.event.release.tag_name }}
     

